spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/also_hyuil?characterEncoding=utf8&autoReconnect=true
    username: holiday
    password: 9595
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.naver.com #smtp ?? ??
    port: 465 # ?? ???? ??
    username: bengi0 #??? ???
    password: in828282 #??? ????
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true #??? ?? -> SSL ??? ?????

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 446949619356-if6qh7v4pve82n6p62096h9ana03fsms.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/google
          naver:
            client-id: jzBSSjHy6lAluTVYYlOq
            client-secret: XeuwygjJLV
            scope:
              - name
              - email
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/naver
          kakao:
            client-id: 172c887a980e386869b959b384c1ea69
            client-secret: faslVe3IGfPOoP6pce9yEqjGAbPiw8Kt
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/kakao
            client-authentication-method: POST
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org:
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG
# Value ??
mail.id: bengi0@naver.com

file.fan.letter.path: C:\IntelliJ\also_hyuil\src\main\resources\static\fanLetter\img_1\

token.valid.time: 864000
token.secret.key: MIIDYTCCAkmgAwIBAgIEQvBInjANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwI4MjEOMAwGA1UECBMFa29yZWExEDAOBgNVBAcTB2J1Y2hlb24xDTALBgNVBAoTBGthbmcxDTALBgNVBAsTBGthbmcxEjAQBgNVBAMTCWthbmdoeXVpbDAeFw0yMzAxMjUwNTUxMThaFw0yMzA0MjUwNTUxMThaMGExCzAJBgNVBAYTAjgyMQ4wDAYDVQQIEwVrb3JlYTEQMA4GA1UEBxMHYnVjaGVvbjENMAsGA1UEChMEa2FuZzENMAsGA1UECxMEa2FuZzESMBAGA1UEAxMJa2FuZ2h5dWlsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArTihhS2vS4hr5B+89KaGYkGH5nzqoimtRGlNLnVpzDlbBpTXoto6OaHEyaSNDac3phkzRjHVuRTtpJ+x1ycO+Pnw6/Rwg/k3FzbH9bhkm3iEp8t8kCq++KnyT2O1+Zr8OmFm3UkGW0unhiFGLRzAGHyreYICVlgCJl0esrXy3qK1z5Q6tHRDzohLkdq66kNIIm8MMMuZElt5k0KxpWVrDSF625kVYm3CphQvPF0Xc8F4MPlAnPNSqCpIH7lcZslvGksNiUWqhGedeikcn27Q4x6yKe213/vYbEc+yAh3o7utO3px2KtzruIMWqhMRVlYFqVkLQL0zL0nsrdGT/8ZlQIDAQABoyEwHzAdBgNVHQ4EFgQUj9L+IQKcaG0j7WDKu64qtUdeLDIwDQYJKoZIhvcNAQELBQADggEBACjoeACZwgefI4fC7QfXS9FWQ7pC54XAXHlVYsbk6UAB0+3sr0aL0gxCtq+BXBD7LAKa1QT9Zab+UQyq+EMTS489G210DaYvHVh3ks3vtXzsOcNzOWowArwxteI/B8MEyy4Mx/udpR2jIp136e3Jd3i0VbXg9bBp5DLzvMC+06vg8yG7ok98vheYZtI3tQUDVirxAmdzMG+dYH6IpLLlwY2bmLEMwa57Csf70Un/QfgLfmKdabJeRDuq1OQIRRJf9U0ns2FZH1DFhGPRgP32j4C6mHCEu9YcAe2blU6027sH8XqUu+8NdjQOcZJOySvSBGlfur/bVgiHPyrn86ZMx4k=
token.access: access_token
token.refresh: refresh_token

token:
  keys:
    kakao:
      kid:
        first: 3f96980381e451efad0d2ddd30e3d3
        second: 9f252dadd5f233f93d2fa528d12fea
      kty:
        first: RSA
        second: RSA
      alg:
        first: RS256
        second: RS256
      use:
        first: sig
        second: sig
      n:
        first: q8zZ0b_MNaLd6Ny8wd4cjFomilLfFIZcmhNSc1ttx_oQdJJZt5CDHB8WWwPGBUDUyY8AmfglS9Y1qA0_fxxs-ZUWdt45jSbUxghKNYgEwSutfM5sROh3srm5TiLW4YfOvKytGW1r9TQEdLe98ork8-rNRYPybRI3SKoqpci1m1QOcvUg4xEYRvbZIWku24DNMSeheytKUz6Ni4kKOVkzfGN11rUj1IrlRR-LNA9V9ZYmeoywy3k066rD5TaZHor5bM5gIzt1B4FmUuFITpXKGQZS5Hn_Ck8Bgc8kLWGAU8TzmOzLeROosqKE0eZJ4ESLMImTb2XSEZuN1wFyL0VtJw
        second: qGWf6RVzV2pM8YqJ6by5exoixIlTvdXDfYj2v7E6xkoYmesAjp_1IYL7rzhpUYqIkWX0P4wOwAsg-Ud8PcMHggfwUNPOcqgSk1hAIHr63zSlG8xatQb17q9LrWny2HWkUVEU30PxxHsLcuzmfhbRx8kOrNfJEirIuqSyWF_OBHeEgBgYjydd_c8vPo7IiH-pijZn4ZouPsEg7wtdIX3-0ZcXXDbFkaDaqClfqmVCLNBhg3DKYDQOoyWXrpFKUXUFuk2FTCqWaQJ0GniO4p_ppkYIf4zhlwUYfXZEhm8cBo6H2EgukntDbTgnoha8kNunTPekxWTDhE5wGAt6YpT4Yw
      e:
        first: AQAB
        second: AQAB
    google:
      kid:
        first: 1aae8d7c92058b5eea456895bf89084571e306f3
        second: acda360fb36cd15ff83af83e173f47ffc36d111c
      kty:
        first: RSA
        second: RSA
      alg:
        first: RS256
        second: RS256
      use:
        first: sig
        second: sig
      n:
        first: sguIKIvlEVBsEGk77iV2yNQxpY_Qkiy3yuMfY4wpmnPlevlDKASu6uP_CGubzThiBHlChYDDNvYfOitWXDwpxbJ_MqmajA-dDbrI5LdggyJpSoWPKThPJ1CKRhRiRXJjXGi6Gg6TfbYRwu0ziyDgZZ125NszuNOUO1pc1qGun4SPifzY7OY6BtADZDqTWHFTfm_yhgBgyElE-r4d-ZqPe9tYYqCnAvILBuZbPYt3UC3fAr9JltdUO54vxKblo2z2fd-H9zBn9jRZOBkuVVB8QSV5sre-H23CTBABSpZpe0SrJpXgG9AuV4Da7FRHBC9A-oLYLe-UF5_5c6_cd7c_KQ
        second: r54td3hTv87IwUNhdc-bYLIny4tBVcasvdSd7lbJILg58C4DJ0RJPczXd_rlfzzYGvgpt3Okf_anJd5aah196P3bqwVDdelcDYAhuajBzn40QjOBPefvdD5zSo18i7OtG7nhAhRSEGe6Pjzpck3wAogqYcDgkF1BzTsRB-DkxprsYhp5pmL5RnX-6EYP5t2m9jJ-_oP9v1yvZkT5UPb2IwOk5GDllRPbvp-aJW_RM18ITU3qIbkwSTs1gJGFWO7jwnxT0QBaFD8a8aev1tmR50ehK-Sz2ORtvuWBxbzTqXXL39qgNJaYwZyW-2040vvuZnaGribcxT83t3cJlQdMxw
      e:
        first: AQAB
        second: AQAB

