### Fanletter write
POST http://localhost:8080/fanLetter/comment/write
Content-Type: application/json

{
  "boardNum": null,
  "commentNum": null,
  "content": ""
}

### FanLetter Remove
DELETE http://localhost:8080/fanLetter/comment/remove?id=1
Content-Type: application/json

{
  "id": 1
}